import React from 'react';
import {Image} from 'react-native';
import tw from 'twrnc';

/*ICONS*/
import IconFAW5 from 'react-native-vector-icons/FontAwesome5';
import IconFAW from 'react-native-vector-icons/FontAwesome';
import IconMI from 'react-native-vector-icons/MaterialIcons';
import IconMCI from 'react-native-vector-icons/MaterialCommunityIcons';
import IconANT from 'react-native-vector-icons/AntDesign';
import IconOCT from 'react-native-vector-icons/Octicons';
import IconION from 'react-native-vector-icons/Ionicons';
import IconSLI from 'react-native-vector-icons/SimpleLineIcons';
import IconFTO from 'react-native-vector-icons/Fontisto';
import IconEn from 'react-native-vector-icons/Entypo';
import IconFTH from 'react-native-vector-icons/Feather';
import IconFUN from 'react-native-vector-icons/Foundation';
import {iconsColor, smoothColor, smoothColor_} from './Colors';

export const usersIcon = <IconFAW name="users" size={24} color={'#333'}/>;
export const handsIcon = <IconFAW name="handshake-o" size={24} color={'#333'}/>;
export const moneyIcon = <IconFAW name="money" size={18} color={'#007ee7'}/>;
export const buildIcon = <IconFAW name="building-o" size={18} color={'#007ee7'}/>;
export const sendIcon = <IconFAW name="send-o" size={20} color={'white'}/>;
export const townIcon = <IconANT name="home" size={24} color={'#007ee7'}/>;
export const idUserIcon = <IconANT name="idcard" size={24} color={'#333'}/>;
export const phoneIcon = <IconANT name="phone" size={24} color={'#333'}/>;
export const homeIcon = <IconANT name="home" size={18} color={'#007ee7'}/>;
export const carIcon = <IconANT name="car" size={18} color={'#007ee7'}/>;
export const deleteIcon = <IconANT name="delete" size={20} color={''}/>;
export const deleteIcon_ = <IconANT name="delete" size={26} color={'#ff5969'}/>;
export const passwordIcon = <IconMCI name="form-textbox-password" size={24} color={'#333'}/>;
export const myTripsIcon = <IconMCI name="layers-triple-outline" size={24} color={'gray'}/>;
export const monthIcon = <IconMCI name="calendar-month-outline" size={28} color={'gray'}/>;
export const loginIcon = <IconMCI name="login-variant" size={24} color={'white'}/>;
export const build_Icon = <IconMCI name="office-building-cog-outline" size={28} color={'white'}/>;
export const userIcon = <IconANT name="user" size={24} color={'#333'}/>;
export const emailIcon = <IconFTO name="email" size={24} color={iconsColor}/>;
export const emailIcon_2 = <IconFTO name="email" size={20} color={'#fff'}/>;
export const celIcon = <IconION name="ios-phone-portrait-outline" size={24} color={'#333'}/>;
export const playIcon = <IconION name="play" size={20} color={'#333'}/>;
export const hidePwdIcon = <IconION name="eye-off-outline" size={24} color={iconsColor}/>;
export const showPwdIcon = <IconION name="eye-outline" size={24} color={iconsColor}/>;
export const imagesIcon = <IconION name="ios-images-outline" size={40} color={smoothColor}/>;
export const settingsIcon = <IconION name="ios-settings-outline" size={56} color={'#fff'}/>;
export const arrowRRIcon = <IconION name="ios-cloud-download-outline" size={30} color={'#fff'}/>;
export const arrowBIcon = <IconION name="arrow-back-circle" size={36} color={'#000'}/>;
export const checkIcon_ = <IconION name="checkmark-done-sharp" size={18} color={'green'}/>;
export const closeIcon = <IconION name="close-circle-outline" size={24} color={'gray'}/>;
export const warnIcon = <IconION name="warning-outline" size={24} color={'#ffa44c'}/>;
export const checkIcon = <IconION name="checkmark-circle-sharp" size={42} color={'red'}/>;
export const checkModalIcon = <IconION name="checkmark-circle-sharp" size={24} color={'white'}/>;
export const cancelIcon = <IconMI name="cancel" size={40} color={'red'}/>;
export const cancelModalIcon = <IconMI name="cancel" size={24} color={'red'}/>;
export const errorIcon = <IconMI name="error" size={24} color={'red'}/>;
export const arrowRIcon = <IconMI name="arrow-forward-ios" size={32} color={'#c0c4c1'}/>;
export const arrowRIcon_ = <IconMI name="arrow-forward-ios" size={24} color={'#333'}/>;
export const arrowRIcon_1 = <IconMI name="arrow-right" size={28} color={'#333'} style={tw`ml-2`}/>;
export const arrowRIcon_2 = <IconMI name="arrow-right" size={34} color={'white'}/>;
export const arrowRIcon_3 = <IconMI name="arrow-right" size={34} color={'white'}/>;
export const arrowLIcon = <IconMI name="arrow-left" size={34} color={'white'}/>;
export const arrowUpIcon = <IconMI name="keyboard-arrow-up" size={28} color={'teal'}/>;
export const arrowDownIcon = <IconMI name="keyboard-arrow-down" size={28} color={'teal'}/>;
export const bookingsIcon = <IconMCI name="format-list-checkbox" size={28} color={'gray'}/>;
export const paymentIcon = <IconMCI name="credit-card-check-outline" size={28} color={'gray'}/>;
export const bellIcon = <IconMCI name="bell-ring-outline" size={28} color={'gray'}/>;
export const boardIcon = <IconMCI name="bulletin-board" size={28} color={'white'}/>;
export const sendMailIcon = <IconMCI name="email-send-outline" size={24} color={'white'}/>;
export const savedIcon = <IconMCI name="content-save-all-outline" size={28} color={'white'}/>;
export const saveBottomModalIcon = <IconMCI name="content-save-all-outline" size={20} color={'#333'}/>;
export const refreshModalIcon = <IconMCI name="refresh" size={20} color={'#333'}/>;
export const deleteModalIcon = <IconMCI name="delete-outline" size={20} color={'#333'}/>;
export const savedIcon_2 = <IconMCI name="content-save-all-outline" size={24} color={'teal'}/>;
export const guestsIcon = <IconION name="person-add-outline" size={28} color={'white'}/>;
export const imageIcon = <IconION name="ios-images-outline" size={56} color={'white'}/>;
export const calendarIcon = <IconMCI name="calendar-month" size={56} color={'white'}/>;
export const accountEditIcon = <IconMCI name="account-edit-outline" size={28} color={'white'}/>;
export const rulesIcon = <IconMCI name="check-decagram-outline" size={18} color={'#0c8478'}/>;
export const emailSendIcon = <IconMCI name="email-send-outline" size={22} color={'#007ee7'}/>;
export const accountStatusIcon = <IconFAW5 name="coins" size={28} color={'white'}/>;
export const storeIcon = <IconMCI name="storefront-outline" size={28} color={'white'}/>;
export const logoutIcon = <IconMCI name="logout-variant" size={30} color={smoothColor}/>;
export const presentIcon = <IconSLI name="present" size={28} color={'gray'}/>;
export const conditionsIcon = <IconION name="ios-document-text-outline" size={28} color={'gray'}/>;
export const confirmIcon = <IconEn name="500px-with-circle" size={40} color={'#007ee7'}/>;
export const downloadIcon = <IconEn name="download" size={56} color={'white'}/>;
export const registerIcon = <IconOCT name="checklist" size={56} color={'white'}/>;
export const checkcircleoIcon = <IconANT name="checkcircleo" size={20} color={'green'}/>;
export const personalDataIcon = <IconFTH name="user-check" size={18} color={'#007ee7'}/>;
export const editIcon = <IconFUN name="page-edit" size={26} color={'#120F72'}/>;
export const percentIcon = <IconMCI name="label-percent-outline" size={24} color={'#0c8478'}/>;
export const paperclipIcon = <IconFAW name="paperclip" size={24} color={'#0c8478'}/>;

/*IMAGES*/

import avatar from '../../assets/img/avatar.png';
import workOrder from '../../assets/img/workOrder.png';
import download from '../../assets/img/download.png';
import advanced from '../../assets/img/advanced.png';
import logoApp from '../../assets/img/logoApp.png';
import logout from '../../assets/img/logout.png';
import settings from '../../assets/img/settings.png';
import settings_ from '../../assets/img/settings_.png';
import models from '../../assets/img/models.png';
import rightArrow from '../../assets/img/rightArrow.png';
import chapter from '../../assets/img/chapter.png';
import reviewStates from '../../assets/img/reviewStates.png';
import add from '../../assets/img/add.png';
import uploadRandom from '../../assets/img/uploadRandom.png';
import period from '../../assets/img/period.png';
import upload from '../../assets/img/uploadImg.png';
import detailWorkOrders from '../../assets/img/detailWorkOrders.png';

export const avatarImg = <Image source={avatar} style={{width: 50, height: 50}}/>;
export const logoAppImg_ = <Image source={logoApp} style={{width: 50, height: 50}}/>;
export const logoAppImg = <Image source={logoApp} style={{width: 50, height: 50}}/>;
export const workOrderImg = <Image source={workOrder} style={{width: 40, height: 40}}/>;
export const advancedImg = <Image source={advanced} style={{width: 40, height: 40}}/>;
export const downloadImg = <Image source={download} style={{width: 25, height: 25}}/>;
export const settingsImg = <Image source={settings} style={{width: 30, height: 30}}/>;
export const logoutImg = <Image source={logout} style={{width: 39, height: 39}}/>;
export const addImg = <Image source={add} style={{width: 39, height: 39}}/>;
export const settingsImg_ = <Image source={settings_} style={{width: 40, height: 40}}/>;
export const modelsImg = <Image source={models} style={{width: 40, height: 40}}/>;
export const chapterImg = <Image source={chapter} style={{width: 37, height: 37}}/>;
export const rightArrowImg = <Image source={rightArrow} style={{width: 40, height: 40}}/>;
export const reviewStatesImg = <Image source={reviewStates} style={{width: 38, height: 38}}/>;
export const uploadRandomImg = <Image source={uploadRandom} style={{width: 38, height: 38}}/>;
export const periodImg = <Image source={period} style={{width: 38, height: 38}}/>;
export const uploadImg = <Image source={upload} style={{width: 38, height: 38}}/>;
export const detailWorkOrdersImg = <Image source={detailWorkOrders} style={{width: 40, height: 40}}/>;
